"""Phase-1 universe: S&P 500 leaders + theme-relevant midcaps across 11 sectors,
plus the ETF set the capital-flow engine watches. CIKs are resolved at runtime from
the SEC's public ticker map, so nothing here needs maintenance when CIKs change."""
from __future__ import annotations

SECTOR_ETF = {
    "Technology": "XLK",
    "Communication Services": "XLC",
    "Consumer Discretionary": "XLY",
    "Consumer Staples": "XLP",
    "Health Care": "XLV",
    "Financials": "XLF",
    "Industrials": "XLI",
    "Energy": "XLE",
    "Materials": "XLB",
    "Utilities": "XLU",
    "Real Estate": "XLRE",
}

# ticker -> (name, sector, industry, size)
COMPANIES: dict[str, tuple[str, str, str, str]] = {
    # Technology
    "AAPL": ("Apple", "Technology", "Consumer Electronics", "large"),
    "MSFT": ("Microsoft", "Technology", "Software", "large"),
    "NVDA": ("NVIDIA", "Technology", "Semiconductors", "large"),
    "AVGO": ("Broadcom", "Technology", "Semiconductors", "large"),
    "AMD": ("Advanced Micro Devices", "Technology", "Semiconductors", "large"),
    "ORCL": ("Oracle", "Technology", "Software", "large"),
    "CRM": ("Salesforce", "Technology", "Software", "large"),
    "ADBE": ("Adobe", "Technology", "Software", "large"),
    "NOW": ("ServiceNow", "Technology", "Software", "large"),
    "INTU": ("Intuit", "Technology", "Software", "large"),
    "QCOM": ("Qualcomm", "Technology", "Semiconductors", "large"),
    "TXN": ("Texas Instruments", "Technology", "Semiconductors", "large"),
    "AMAT": ("Applied Materials", "Technology", "Semiconductor Equipment", "large"),
    "LRCX": ("Lam Research", "Technology", "Semiconductor Equipment", "large"),
    "KLAC": ("KLA", "Technology", "Semiconductor Equipment", "large"),
    "MU": ("Micron Technology", "Technology", "Semiconductors", "large"),
    "ANET": ("Arista Networks", "Technology", "Networking", "large"),
    "PANW": ("Palo Alto Networks", "Technology", "Cybersecurity", "large"),
    "CRWD": ("CrowdStrike", "Technology", "Cybersecurity", "large"),
    "FTNT": ("Fortinet", "Technology", "Cybersecurity", "large"),
    "ZS": ("Zscaler", "Technology", "Cybersecurity", "mid"),
    "NET": ("Cloudflare", "Technology", "Cloud Infrastructure", "mid"),
    "SNPS": ("Synopsys", "Technology", "EDA Software", "large"),
    "CDNS": ("Cadence Design Systems", "Technology", "EDA Software", "large"),
    "MRVL": ("Marvell Technology", "Technology", "Semiconductors", "large"),
    "PLTR": ("Palantir Technologies", "Technology", "Software", "large"),
    "SNOW": ("Snowflake", "Technology", "Software", "mid"),
    "DDOG": ("Datadog", "Technology", "Software", "mid"),
    "APP": ("AppLovin", "Technology", "Ad Tech", "large"),
    "CRDO": ("Credo Technology", "Technology", "Semiconductors", "mid"),
    "ALAB": ("Astera Labs", "Technology", "Semiconductors", "mid"),
    "COHR": ("Coherent", "Technology", "Optical Components", "mid"),
    "CIEN": ("Ciena", "Technology", "Networking", "mid"),
    "TER": ("Teradyne", "Technology", "Semiconductor Equipment", "mid"),
    "FSLR": ("First Solar", "Technology", "Solar", "mid"),
    "TTD": ("The Trade Desk", "Technology", "Ad Tech", "mid"),
    # Communication Services
    "GOOGL": ("Alphabet", "Communication Services", "Internet", "large"),
    "META": ("Meta Platforms", "Communication Services", "Internet", "large"),
    "NFLX": ("Netflix", "Communication Services", "Streaming", "large"),
    "TMUS": ("T-Mobile US", "Communication Services", "Telecom", "large"),
    "DIS": ("Walt Disney", "Communication Services", "Media", "large"),
    "CMCSA": ("Comcast", "Communication Services", "Media", "large"),
    "RBLX": ("Roblox", "Communication Services", "Gaming", "mid"),
    "RDDT": ("Reddit", "Communication Services", "Internet", "mid"),
    # Consumer Discretionary
    "AMZN": ("Amazon", "Consumer Discretionary", "E-commerce / Cloud", "large"),
    "TSLA": ("Tesla", "Consumer Discretionary", "Autos", "large"),
    "HD": ("Home Depot", "Consumer Discretionary", "Home Improvement", "large"),
    "LOW": ("Lowe's", "Consumer Discretionary", "Home Improvement", "large"),
    "MCD": ("McDonald's", "Consumer Discretionary", "Restaurants", "large"),
    "NKE": ("Nike", "Consumer Discretionary", "Apparel", "large"),
    "BKNG": ("Booking Holdings", "Consumer Discretionary", "Travel", "large"),
    "SBUX": ("Starbucks", "Consumer Discretionary", "Restaurants", "large"),
    "TJX": ("TJX Companies", "Consumer Discretionary", "Off-price Retail", "large"),
    "TSCO": ("Tractor Supply", "Consumer Discretionary", "Retail", "mid"),
    "UBER": ("Uber Technologies", "Consumer Discretionary", "Mobility", "large"),
    "ABNB": ("Airbnb", "Consumer Discretionary", "Travel", "large"),
    "MAR": ("Marriott International", "Consumer Discretionary", "Lodging", "large"),
    "RCL": ("Royal Caribbean", "Consumer Discretionary", "Cruise Lines", "large"),
    "DHI": ("D.R. Horton", "Consumer Discretionary", "Homebuilders", "large"),
    "LEN": ("Lennar", "Consumer Discretionary", "Homebuilders", "large"),
    "PHM": ("PulteGroup", "Consumer Discretionary", "Homebuilders", "mid"),
    "TOL": ("Toll Brothers", "Consumer Discretionary", "Homebuilders", "mid"),
    # Consumer Staples
    "PG": ("Procter & Gamble", "Consumer Staples", "Household Products", "large"),
    "KO": ("Coca-Cola", "Consumer Staples", "Beverages", "large"),
    "PEP": ("PepsiCo", "Consumer Staples", "Beverages", "large"),
    "COST": ("Costco", "Consumer Staples", "Warehouse Retail", "large"),
    "WMT": ("Walmart", "Consumer Staples", "Retail", "large"),
    "PM": ("Philip Morris International", "Consumer Staples", "Tobacco", "large"),
    "MDLZ": ("Mondelez", "Consumer Staples", "Packaged Food", "large"),
    # Health Care
    "LLY": ("Eli Lilly", "Health Care", "Pharma", "large"),
    "UNH": ("UnitedHealth Group", "Health Care", "Managed Care", "large"),
    "JNJ": ("Johnson & Johnson", "Health Care", "Pharma", "large"),
    "ABBV": ("AbbVie", "Health Care", "Pharma", "large"),
    "MRK": ("Merck", "Health Care", "Pharma", "large"),
    "PFE": ("Pfizer", "Health Care", "Pharma", "large"),
    "AMGN": ("Amgen", "Health Care", "Biotech", "large"),
    "TMO": ("Thermo Fisher Scientific", "Health Care", "Life Science Tools", "large"),
    "DHR": ("Danaher", "Health Care", "Life Science Tools", "large"),
    "ISRG": ("Intuitive Surgical", "Health Care", "Medical Devices", "large"),
    "ABT": ("Abbott Laboratories", "Health Care", "Medical Devices", "large"),
    "BSX": ("Boston Scientific", "Health Care", "Medical Devices", "large"),
    "SYK": ("Stryker", "Health Care", "Medical Devices", "large"),
    "EW": ("Edwards Lifesciences", "Health Care", "Medical Devices", "mid"),
    "DXCM": ("DexCom", "Health Care", "Medical Devices", "mid"),
    "VRTX": ("Vertex Pharmaceuticals", "Health Care", "Biotech", "large"),
    "REGN": ("Regeneron", "Health Care", "Biotech", "large"),
    # Financials
    "JPM": ("JPMorgan Chase", "Financials", "Banks", "large"),
    "BAC": ("Bank of America", "Financials", "Banks", "large"),
    "WFC": ("Wells Fargo", "Financials", "Banks", "large"),
    "C": ("Citigroup", "Financials", "Banks", "large"),
    "GS": ("Goldman Sachs", "Financials", "Investment Banking", "large"),
    "MS": ("Morgan Stanley", "Financials", "Investment Banking", "large"),
    "V": ("Visa", "Financials", "Payments", "large"),
    "MA": ("Mastercard", "Financials", "Payments", "large"),
    "AXP": ("American Express", "Financials", "Payments", "large"),
    "PYPL": ("PayPal", "Financials", "Payments", "large"),
    "XYZ": ("Block", "Financials", "Payments", "mid"),
    "SOFI": ("SoFi Technologies", "Financials", "Fintech", "mid"),
    "HOOD": ("Robinhood Markets", "Financials", "Brokerage", "mid"),
    "COIN": ("Coinbase", "Financials", "Crypto Exchange", "mid"),
    "IBKR": ("Interactive Brokers", "Financials", "Brokerage", "mid"),
    "SCHW": ("Charles Schwab", "Financials", "Brokerage", "large"),
    "BLK": ("BlackRock", "Financials", "Asset Management", "large"),
    "CME": ("CME Group", "Financials", "Exchanges", "large"),
    "ICE": ("Intercontinental Exchange", "Financials", "Exchanges", "large"),
    "SPGI": ("S&P Global", "Financials", "Data & Ratings", "large"),
    "PGR": ("Progressive", "Financials", "Insurance", "large"),
    # Industrials
    "GE": ("GE Aerospace", "Industrials", "Aerospace", "large"),
    "GEV": ("GE Vernova", "Industrials", "Power Equipment", "large"),
    "CAT": ("Caterpillar", "Industrials", "Machinery", "large"),
    "ETN": ("Eaton", "Industrials", "Electrical Equipment", "large"),
    "HON": ("Honeywell", "Industrials", "Conglomerate", "large"),
    "UNP": ("Union Pacific", "Industrials", "Rail", "large"),
    "RTX": ("RTX", "Industrials", "Aerospace & Defense", "large"),
    "LMT": ("Lockheed Martin", "Industrials", "Defense", "large"),
    "NOC": ("Northrop Grumman", "Industrials", "Defense", "large"),
    "GD": ("General Dynamics", "Industrials", "Defense", "large"),
    "LHX": ("L3Harris", "Industrials", "Defense", "large"),
    "HWM": ("Howmet Aerospace", "Industrials", "Aerospace", "large"),
    "DE": ("Deere", "Industrials", "Machinery", "large"),
    "PH": ("Parker-Hannifin", "Industrials", "Machinery", "large"),
    "EMR": ("Emerson Electric", "Industrials", "Automation", "large"),
    "ROK": ("Rockwell Automation", "Industrials", "Automation", "mid"),
    "VRT": ("Vertiv", "Industrials", "Datacenter Equipment", "large"),
    "PWR": ("Quanta Services", "Industrials", "Infrastructure Services", "large"),
    "HUBB": ("Hubbell", "Industrials", "Electrical Equipment", "mid"),
    "NVT": ("nVent Electric", "Industrials", "Electrical Equipment", "mid"),
    "FIX": ("Comfort Systems USA", "Industrials", "Mechanical Contracting", "mid"),
    "MOD": ("Modine Manufacturing", "Industrials", "Thermal Management", "mid"),
    "URI": ("United Rentals", "Industrials", "Equipment Rental", "large"),
    "ADP": ("Automatic Data Processing", "Industrials", "HR Software", "large"),
    "AXON": ("Axon Enterprise", "Industrials", "Public Safety Tech", "mid"),
    "RKLB": ("Rocket Lab", "Industrials", "Space", "mid"),
    "UPS": ("United Parcel Service", "Industrials", "Logistics", "large"),
    "FDX": ("FedEx", "Industrials", "Logistics", "large"),
    "DAL": ("Delta Air Lines", "Industrials", "Airlines", "mid"),
    "BLDR": ("Builders FirstSource", "Industrials", "Building Products", "mid"),
    # Energy
    "XOM": ("Exxon Mobil", "Energy", "Integrated Oil", "large"),
    "CVX": ("Chevron", "Energy", "Integrated Oil", "large"),
    "COP": ("ConocoPhillips", "Energy", "E&P", "large"),
    "EOG": ("EOG Resources", "Energy", "E&P", "large"),
    "OXY": ("Occidental Petroleum", "Energy", "E&P", "large"),
    "SLB": ("Schlumberger", "Energy", "Oilfield Services", "large"),
    "BKR": ("Baker Hughes", "Energy", "Oilfield Services", "large"),
    "LNG": ("Cheniere Energy", "Energy", "LNG", "large"),
    "EQT": ("EQT", "Energy", "Natural Gas E&P", "mid"),
    "KMI": ("Kinder Morgan", "Energy", "Midstream", "large"),
    "WMB": ("Williams Companies", "Energy", "Midstream", "large"),
    # Materials
    "LIN": ("Linde", "Materials", "Industrial Gases", "large"),
    "SHW": ("Sherwin-Williams", "Materials", "Coatings", "large"),
    "FCX": ("Freeport-McMoRan", "Materials", "Copper", "large"),
    "SCCO": ("Southern Copper", "Materials", "Copper", "large"),
    "NEM": ("Newmont", "Materials", "Gold", "large"),
    "APD": ("Air Products", "Materials", "Industrial Gases", "large"),
    "NUE": ("Nucor", "Materials", "Steel", "large"),
    # Utilities
    "NEE": ("NextEra Energy", "Utilities", "Utilities", "large"),
    "SO": ("Southern Company", "Utilities", "Utilities", "large"),
    "DUK": ("Duke Energy", "Utilities", "Utilities", "large"),
    "AEP": ("American Electric Power", "Utilities", "Utilities", "large"),
    "CEG": ("Constellation Energy", "Utilities", "Independent Power", "large"),
    "VST": ("Vistra", "Utilities", "Independent Power", "large"),
    "NRG": ("NRG Energy", "Utilities", "Independent Power", "mid"),
    "BWXT": ("BWX Technologies", "Industrials", "Nuclear Components", "mid"),
    # Real Estate
    "PLD": ("Prologis", "Real Estate", "Logistics REIT", "large"),
    "AMT": ("American Tower", "Real Estate", "Tower REIT", "large"),
    "EQIX": ("Equinix", "Real Estate", "Datacenter REIT", "large"),
    "DLR": ("Digital Realty", "Real Estate", "Datacenter REIT", "large"),
    "O": ("Realty Income", "Real Estate", "Net Lease REIT", "large"),
    "SPG": ("Simon Property Group", "Real Estate", "Retail REIT", "large"),
}

# symbol -> (name, group, sector)
INSTRUMENTS: dict[str, tuple[str, str, str | None]] = {
    # benchmark / breadth
    "SPY": ("S&P 500", "benchmark", None),
    "RSP": ("S&P 500 Equal Weight", "benchmark", None),
    "^VIX": ("CBOE Volatility Index", "benchmark", None),
    # sectors
    "XLK": ("Technology", "sector", "Technology"),
    "XLC": ("Communication Services", "sector", "Communication Services"),
    "XLY": ("Consumer Discretionary", "sector", "Consumer Discretionary"),
    "XLP": ("Consumer Staples", "sector", "Consumer Staples"),
    "XLV": ("Health Care", "sector", "Health Care"),
    "XLF": ("Financials", "sector", "Financials"),
    "XLI": ("Industrials", "sector", "Industrials"),
    "XLE": ("Energy", "sector", "Energy"),
    "XLB": ("Materials", "sector", "Materials"),
    "XLU": ("Utilities", "sector", "Utilities"),
    "XLRE": ("Real Estate", "sector", "Real Estate"),
    # industries
    "SMH": ("Semiconductors", "industry", "Technology"),
    "IGV": ("Software", "industry", "Technology"),
    "CIBR": ("Cybersecurity", "industry", "Technology"),
    "SKYY": ("Cloud Computing", "industry", "Technology"),
    "XHB": ("Homebuilders", "industry", "Consumer Discretionary"),
    "KRE": ("Regional Banks", "industry", "Financials"),
    "IAI": ("Broker-Dealers & Exchanges", "industry", "Financials"),
    "KIE": ("Insurance", "industry", "Financials"),
    "ITA": ("Aerospace & Defense", "industry", "Industrials"),
    "PAVE": ("Infrastructure", "industry", "Industrials"),
    "BOTZ": ("Robotics & AI", "industry", "Industrials"),
    "IYT": ("Transportation", "industry", "Industrials"),
    "XBI": ("Biotech", "industry", "Health Care"),
    "IHI": ("Medical Devices", "industry", "Health Care"),
    "XOP": ("Oil & Gas E&P", "industry", "Energy"),
    "XME": ("Metals & Mining", "industry", "Materials"),
    "URA": ("Uranium", "industry", "Energy"),
    "NLR": ("Nuclear Energy", "industry", "Utilities"),
    "GRID": ("Smart Grid Infrastructure", "industry", "Industrials"),
    "ARKK": ("Disruptive Innovation", "industry", None),
    # factors
    "VUG": ("Growth", "factor", None),
    "VTV": ("Value", "factor", None),
    "QUAL": ("Quality", "factor", None),
    "MTUM": ("Momentum", "factor", None),
    "USMV": ("Low Volatility", "factor", None),
    # size
    "IJH": ("Mid Cap", "size", None),
    "IWM": ("Small Cap", "size", None),
    # regions
    "EFA": ("Developed ex-US", "region", None),
    "EEM": ("Emerging Markets", "region", None),
    # bonds
    "TLT": ("20+ Year Treasuries", "bond", None),
    "IEF": ("7-10 Year Treasuries", "bond", None),
    "SHY": ("1-3 Year Treasuries", "bond", None),
    "TIP": ("TIPS", "bond", None),
    "LQD": ("Investment Grade Credit", "bond", None),
    "HYG": ("High Yield Credit", "bond", None),
    # commodities
    "GLD": ("Gold", "commodity", None),
    "SLV": ("Silver", "commodity", None),
    "CPER": ("Copper", "commodity", None),
    "USO": ("Crude Oil", "commodity", None),
    "DBC": ("Broad Commodities", "commodity", None),
    # crypto
    "BTC-USD": ("Bitcoin", "crypto", None),
    "ETH-USD": ("Ethereum", "crypto", None),
}


def company_tickers(limit: int | None = None) -> list[str]:
    t = list(COMPANIES)
    return t[:limit] if limit else t
