"""Theme mapping for the wide universe.

themes.yaml is hand-curated for the thematic seed list. Names added later (S&P 500 index members, tickers added via
search, thesis-driven nominees) are mapped here by the bulk model and stored in brain/theme_exposures_extra.yaml,
which themes.load_graph() merges onto the top-level theme nodes. Curated exposures always win.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

import yaml

from ..llm import _call

EXTRA_PATH = Path(__file__).resolve().parent.parent / "theme_exposures_extra.yaml"

SCHEMA = {"type": "object", "properties": {"mappings": {"type": "array", "items": {"type": "object", "properties": {
    "ticker": {"type": "string"},
    "exposures": {"type": "array", "items": {"type": "object", "properties": {
        "theme_id": {"type": "string"}, "weight": {"type": "number"}, "order": {"type": "integer"}},
        "required": ["theme_id", "weight", "order"], "additionalProperties": False}}},
    "required": ["ticker", "exposures"], "additionalProperties": False}}}, "required": ["mappings"], "additionalProperties": False}
SYSTEM = (
    "You map companies to investment themes. For EACH company in the list return its exposures to the given themes (use theme ids exactly). "
    "weight = the share of the company's revenue/earnings story genuinely tied to the theme, 0.1 to 0.9; order = 1 for a direct first-order "
    "beneficiary, 2 for a supplier/enabler one step removed, 3 for an indirect beneficiary. Be strict: at most three themes per company, and "
    "return an EMPTY exposures list when no theme is a material part of the business (most consumer staples, insurers, diversified banks). "
    "Do not stretch: a bank is not 'AI Software'. Include every company from the list exactly once. No disclaimers. Return only the JSON object requested.")


def load_extra() -> dict[str, dict[str, list]]:
    if not EXTRA_PATH.exists():
        return {}
    return (yaml.safe_load(EXTRA_PATH.read_text()) or {}).get("exposures", {}) or {}


def map_batch(companies: list[dict], themes: list[dict]) -> dict[str, dict[str, list]]:
    out = _call(SYSTEM, {"themes": themes, "companies": companies}, SCHEMA, "theme_map", tier="bulk")
    if not out:
        return {}
    ids, allowed = {t["id"] for t in themes}, {c["ticker"] for c in companies}
    res: dict[str, dict[str, list]] = {}
    for m in out.get("mappings", []):
        if m["ticker"] not in allowed:
            continue
        exp = {e["theme_id"]: [round(min(max(float(e["weight"]), 0.1), 0.9), 2), min(max(int(e["order"]), 1), 3)]
               for e in m.get("exposures", [])[:3] if e["theme_id"] in ids}
        res[m["ticker"]] = exp          # an empty dict records "mapped, no theme" so the name is not re-asked every run
    return res


def save_extra(mapping: dict[str, dict[str, list]], model: Optional[str] = None) -> None:
    header = ("# Generated by `python -m brain.pipeline themes-map` (bulk model). Exposures for names outside themes.yaml:\n"
              "# ticker -> {top-level theme id: [weight, order]}. Empty = reviewed, no material theme. Edit freely; curated themes.yaml wins.\n")
    EXTRA_PATH.write_text(header + yaml.safe_dump({"exposures": dict(sorted(mapping.items()))}, sort_keys=False, default_flow_style=None))
